#!/usr/bin/env python3
"""Recover original world tables and the graphics needed for a new-game view."""
import hashlib
import json
from pathlib import Path
from export_assets import export, load_library
from export_catalog import write_catalog


def c_string(text):
    return json.dumps(text, ensure_ascii=False)


def main():
    lib = load_library(Path('build/libsvea_assets.so'))
    data = export(lib, Path('SveaRike/DATA.CST'), Path('analysis/assets/DATA'), metadata_only=True)
    write_catalog(data)
    prices = export(lib, Path('SveaRike/PRICES.CST'), Path('analysis/assets/PRICES'), metadata_only=True)
    export(lib, Path('SveaRike/SVEA.DIR'), Path('analysis/assets/SVEA'))
    members = {m['number']:m for m in data['members']}
    assert int(members[1]['text'].splitlines()[0]) == 28
    rows = []
    provinces = []
    for number in range(1, 29):
        m = members[number+1]
        lines = m['text'].split('\n')
        assert len(lines[1]) == 1 and lines[1] in 'ABCDEF'
        values = [int(lines[i]) for i in (2,3,4,5,7)]
        rows.append('    {'+', '.join([c_string(lines[0]), c_string(lines[6]), repr(lines[1]), *map(str,values)])+'},')
        provinces.append({'number':number, 'name':lines[0], 'owner':lines[1], 'source_member':number+1,
                          'stxt_resource':m['stxt_resource'], 'raw_sha256':hashlib.sha256(bytes.fromhex(m['text_hex'])).hexdigest()})
    tables = []
    for m in prices['members']:
        values = json.loads(m['text'])
        assert len(values) == 5 and all(type(x) is int and x >= 0 for x in values)
        tables.append('    {'+', '.join(map(str, values))+'}, /* '+m['name']+' */')
    relations = []
    for turn in range(1,61):
        values = [int(x) for x in members[500+turn]['text'].splitlines()[:4]]
        assert len(values)==4
        relations.append('    {'+', '.join(map(str,values))+'},')
    header = ('/* Generated by tools/prepare_strategy.py from original DATA.CST and PRICES.CST. */\n'
              '#ifndef SR_WORLD_DATA_H\n#define SR_WORLD_DATA_H\n'
              'static const SrAreaDef sr_area_defs[28] = {\n'+'\n'.join(rows)+'\n};\n'
              'static const int sr_price_tables[16][5] = {\n'+'\n'.join(tables)+'\n};\n'
              'static const int sr_relation_table[60][4] = {\n'+'\n'.join(relations)+'\n};\n#endif\n')
    target=Path('src/generated/world_data.h')
    target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text(header,encoding='utf-8')
    Path('analysis/world-data-provenance.json').write_text(json.dumps({'data_sha256':data['sha256'],
        'prices_sha256':prices['sha256'], 'provinces':provinces},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    names=['interface rakt.pict','King1','Karta','Farm1','Farm3','Mining1','Milli1','Milli2',
           'HQ1','City1','time1','Första Axel copy','firstOKhi']
    names += [f'Family.{i}' for i in range(1,6)] + [f'Area{i}' for i in range(1,29)]
    names += [f'King{i}' for i in range(1,17)] + [f'time{i}' for i in range(1,61)]
    names += [f'{prefix}{i}' for prefix in ('HQ','City') for i in range(1,6)]
    names += ['Uppror. norm','Rebellion.StrikeHi','Rebellion.TalkHi','Rebellion.GiveInHi','Kravaller norm']
    names += ['Hemförlova norm'] + [f'mTrop{i}' for i in range(1,4)]
    names += ['Fältherrar norm','Milli3.OKhi','Milli3.HireHi']
    names += ['HQ','Herre.OKhi','Kult o veten norm','Cult.OKhi','cult.HireHi']
    names += [f'HQLevel{i}' for i in range(1,6)] + [f'HerreFam.{i}' for i in range(1,6)]
    names += ['Stad norm','Stad.OKhi','Knapp-handel']
    names += ['Grannl.1 norm','Granne.HandelHi','Granne.OKHi','Granne.DiplHi',
              'Dipl norm','Dipl.Grannehi','Dipl.OKhi','Dipl.TradHi','Dipl.up','Dipl.relUp','Dipl.relDown']
    names += ['Handel norm','hand.granne','hand.OK','hand.Dip','hand.up']
    names += ['Krig! norm','War.BattleHi','War.NegHi','War.QuickHi','Snabb, high+förlust',
              'Quick.OKhi','ResultLose','SwedWins','WarResult.OKhi','Välj förläning norm',
              'Location.OKhi','Välj regemente norm','ChooseTroops.OKhi','Pinsamt','Förhandla norm']
    names += [f'{prefix}{i}' for prefix in ('Krig.','miniWar.') for i in range(1,5)]
    names += [f'{prefix}{i}' for prefix in ('TradeIcon','DiplomacyIcon','RelationIcon') for i in range(1,6)]
    names += [f'troopIcon{country}{level}' for country in range(1,5) for level in range(1,4)]
    names += [f'CityLevel{i}' for i in range(1,6)] + [f'Banner.{i}' for i in range(1,51)]
    names += ['Militaria 1 norm','mili.OKhi','Mili.Rek2Hi','Mili.RekHi','Mili.UpgradeHi',
              'Meddelande norm.pict','Error.OKhi']
    names += [f'MilitaryLevel{i}' for i in range(1,6)]
    names += [f'Milli{i}' for i in range(1,6)] + [f'TroopNiv{i}' for i in range(1,4)]
    names += ['Farming','Jord.OKhi','Jord.UpgradeHi','Bergmeny norm','Berg.OKhi','Berg.UpgradeHi']
    for prefix in ('Farm','Mining','FarmLevel','MiningLevel'):
        names += [f'{prefix}{i}' for i in range(1,6)]
    ownership={'A':5,'B':1,'C':4,'D':2,'E':0,'F':3}
    for p in provinces:
        color=ownership[p['owner']]
        if color: names.append(f"{p['number']}_{color}.pct")
    names += [f'{i}_{color}.pct' for i in range(1,29) for color in range(1,7)]
    Path('analysis/strategy-assets.json').write_text(json.dumps(names,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    graphics=export(lib,Path('SveaRike/PICTS.CST'),Path('analysis/assets/PICTS'),selected_names={s.lower() for s in names})
    graphics_by_name={m['name']:m['number'] for m in graphics['members']}
    Path('src/generated/turn_pictures.h').write_text(
        '/* Generated from original PICTS.CST names. */\n'+
        '\n'.join('static const int sr_'+name+'[] = {0,'+','.join(
            str(graphics_by_name[f'{prefix}{i}']) for i in range(1,count+1))+'};'
            for name,prefix,count in [('king_pictures','King',16),('time_pictures','time',60)])+'\n')
    stamps=[]
    for number in range(1,29):
        stamps.append('    {0, '+', '.join(str(graphics_by_name[f'{number}_{color}.pct']) for color in range(1,7))+'},')
    Path('src/generated/map_stamps.h').write_text(
        '/* Generated from original PICTS.CST cast names; resource IDs are not arithmetic. */\n'
        'static const int sr_map_stamps[28][7] = {\n'+'\n'.join(stamps)+'\n};\n')
    print('Generated 28 province definitions, 16 price tables and 60 relationship rows.')


if __name__=='__main__':
    main()
